language: c

addons:
  apt:
    packages:
      - libjson0
      - libjson0-dev
      - lua5.1
      - liblua5.1-0-dev

before_install:
  - sudo apt-get install
  - export CFLAGS="-Wno-error"
  - git clone https://git.openwrt.org/project/libubox.git --depth=1 && cd libubox
  - cmake . && sudo make install && cd ..
  - git clone https://git.openwrt.org/project/uci.git --depth=1 && cd uci
  - cmake . && sudo make install && cd ..
  - sudo ldconfig -v

install:
  - git clone https://github.com/bluebird75/luaunit.git --depth=1
  #- sudo ln -s ./luaunit.lua /usr/share/lua/5.1/luaunit.lua
  - cd luaunit && sudo python doit.py install && cd ..

script:
  - cd openwisp-config/tests/
  - lua test_store_unmanaged.lua -v

branches:
  - master
